PR-72-Create agreement modal
Mariie97/Capstone-QWERTY-Dev-Solutions-Team pull request #17
Opened 2021-11-07 02:28 UTC by xstephaniex

Finished the Agreement Modal🚀!!!

2021-11-08 19:44 UTC, Mariie97 requested changes

2021-11-08 19:44 UTC, Mariie97 commented on parapido-gui/src/Components/AdministrationPage.js
> +        console.log(is_admin)
```suggestion
```

2021-11-08 19:44 UTC, Mariie97 commented on parapido-gui/src/Utilities.js
> +export const current_user = {
Mismo comentario que el PR de myJobsDashboard -> #18

2021-11-08 19:44 UTC, Mariie97 commented on parapido-gui/src/Components/AgreementModal.js
> +        console.log(checked, "inside render")
```suggestion
```

2021-11-08 22:38 UTC, xstephaniex commented
@Mariie97 arregle los cambios como sugeridos, cualquier otro cambio me dejas saber.

2021-11-09 22:14 UTC, Mariie97 commented on parapido-gui/src/Utilities.js
> +export const current_user = {
@xstephaniex Falta eliminar el `current_user` de utilities y hacer el mismo fix que hicistes para el PR de myJobDashboard. En este PR se utilizar mucho `current_user`, hay que asegurarse de arreglar todas las ocurrencias

2021-11-10 02:36 UTC, xstephaniex commented on parapido-gui/src/Utilities.js
> +export const current_user = {
@Mariie97 Acabo de arreglar las sugerencias, tambien traje los nuevos cambios que se entraron al main y se resolvieron los merge conflicts 🚀, para hacer el "pull request mas easy"

2021-11-10 14:52 UTC, Mariie97 approved these changes

2021-11-10 14:52 UTC, merged