PR-80-myJobs-dashboard-page
Mariie97/Capstone-QWERTY-Dev-Solutions-Team pull request #18
Opened 2021-11-08 12:55 UTC by xstephaniex

Finished the myJobs page🚀!!!

2021-11-08 19:09 UTC, Mariie97 requested changes

2021-11-08 19:09 UTC, Mariie97 commented on parapido-gui/src/Layouts/myJobsDashboardCard.css
> +
Eliminar myJobsDashboardPage.css si no es necesario. El file esta vacio

2021-11-08 22:12 UTC, xstephaniex commented on parapido-gui/src/Utilities.js
> +export const current_user = {
@Mariie97 se podría especificar sobre que errores se encontraron en el profile page y nav bar que deba arreglar, me perdi al respecto.

2021-11-09 22:10 UTC, Mariie97 approved these changes

2021-11-09 22:10 UTC, merged